language: ruby
rvm:
- 1.9.3

branches:
  only:
  - development

before_install:
- gem install jekyll
- gem install html-proofer
- npm install -g grunt-cli

install:
- npm install

script:
- grunt
- cd src
- jekyll build
- htmlproof ./_site
