# Site settings
title: Elliot Wright
email: elliot@elliotwright.co
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://elliotwright.co" # the base hostname & protocol for your site
facebook_username: wright.elliot
github_username: SeerUK
linkedin_username: 204674421
twitter_username: SeerUK

# Build settings
markdown: kramdown

# Outputting
permalink: /articles/:year/:month/:day/:title
